### ISSUE TITLE
录制正常但无法上传，显示 新增稿件分P不能为空

### ISSUE THREAD

**Issue by LeseningNano** [AsaChiri/DDRecorder#79]
录制是正常的但是无法上传。log里面显示Exception: {'code': 21011, 'message': '新增稿件分P不能为空', 'ttl': 1}，尝试用了压缩包里面自带的配置文件（改了房间号和鉴权）但仍然不行

**Comment by ZhaoWeicheng98** [comment]
看一看如果是上传切片outputs文件夹中是否有输出的视频片段，如果是上传录播splits文件夹中是否有输出的片段？主要您可以检查一下ffmpeg是否可以正常使用。

**Comment by tang-guo-guo** [comment]
records文件夹里面有视频文件但是在其他文件夹只有一个空文件夹
![image](https://user-images.githubusercontent.com/71223830/201454350-b5128d77-8458-4e4e-90e7-a8c2efc83b5a.png)
![image](https://user-images.githubusercontent.com/71223830/201454365-00fca45a-e0d4-4109-b289-c3c14073e857.png)

**Comment by ZhaoWeicheng98** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:SimSun;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:DengXian;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	***@***.***";
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	***@***.***";
	panose-1:2 1 6 0 3 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:DengXian;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 90.0pt 72.0pt 90.0pt;}
div.WordSection1
	{page:WordSection1;}
***@***.*** From: tang-guo-guoSent: 2022年11月11日 22:31To: AsaChiri/DDRecorderCc: 朝尘; CommentSubject: Re: [AsaChiri/DDRecorder] 录制正常但无法上传，显示 新增稿件分P不能为空 (Issue #79) records文件夹里面有视频文件但是在其他文件夹只有一个空文件夹—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by tang-guo-guo** [comment]
日志提示分p为空
![image](https://user-images.githubusercontent.com/71223830/201459442-cb56733e-d6fe-46e9-8955-1453e5c3ec92.png)
ffmpeg命令正常使用
![image](https://user-images.githubusercontent.com/71223830/201459469-c1377a38-c368-45f4-8b5b-212dae1a3f40.png)

**Comment by ZhaoWeicheng98** [comment]
看起来ffmpeg似乎没有正确处理源视频，您看下log中ffmpeg打头的log呢? From: tang-guo-guoSent: 2022年11月12日 0:50To: AsaChiri/DDRecorderCc: 朝尘; CommentSubject: Re: [AsaChiri/DDRecorder] 录制正常但无法上传，显示 新增稿件分P不能为空 (Issue #79) 日志提示分p为空ffmpeg命令正常使用—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by tang-guo-guo** [comment]
![image](https://user-images.githubusercontent.com/71223830/201459673-556b57b6-3a5a-4e37-8984-9aa18aff0525.png)
log提示ffmpeg不是内部指令,

**Comment by ZhaoWeicheng98** [comment]
您可以再次尝试运行看看问题是否仍然存在（看起来是初次运行配置后没有及时生效导致） From: tang-guo-guoSent: 2022年11月12日 1:00To: AsaChiri/DDRecorderCc: 朝尘; CommentSubject: Re: [AsaChiri/DDRecorder] 录制正常但无法上传，显示 新增稿件分P不能为空 (Issue #79) log提示ffmpeg不是内部指令,—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by tang-guo-guo** [comment]
好我今天在测试一下

**Comment by tang-guo-guo** [comment]
> 您可以再次尝试运行看看问题是否仍然存在（看起来是初次运行配置后没有及时生效导致） 来自： 唐国发送： 2022年11月12日 1：00至： 朝千里/DDRecorderCc： 朝尘;评论主题： 回复： [AsaChiri/DDRecorder] 录制正常但无法上传，显示 新增稿件分P不能为空 （Issue#79） log提示ffmpeg不是内部指令，—直接回复此电子邮件，在GitHub上查看或取消订阅。您收到此消息是因为您发表了评论。消息 ID：***@***.***>

在问一下如果腾讯云服务器设置内网cos传输是这样子设置吗,设置完成之后好像没上传文件了
![image](https://user-images.githubusercontent.com/71223830/201529235-0e7610ce-aafc-4740-9a88-e3628011e7a5.png)

**Comment by ZhaoWeicheng98** [comment]
应该是这样设置的。
另外此问题可以参见#87 看看有没有修好这个问题？
